spring.datasource.url=jdbc:postgresql://localhost:5432/librarysite
spring.datasource.username=postgres
spring.datasource.password=Taelar951!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>